gbifpublishers.settings:
  type: config_object
  label: 'GBIF Publishers settings'
  mapping:
    gbifpublishers:
      type: mapping
      mapping:
        uuid_code:
          type: text
          label: 'Le code UUID du pays :'